<a href="https://colab.research.google.com/github/szeyeoh/NumPy-Machine-Learning/blob/main/NumPy_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

data = pd.read_csv("/content/sample_data/mnist_test.csv")

In [ ]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [ ]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2
def ReLU(Z):
    return np.maximum(Z, 0)
def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0
def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y
def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2

In [ ]:
def get_predictions(A2):
    return np.argmax(A2, 0)
def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size
def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [ ]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 1, 500)


Iteration:  0
[1 2 8 ... 8 1 2] [2 2 9 ... 5 7 7]
0.06522946994110457
Iteration:  10
[7 2 7 ... 7 7 7] [2 2 9 ... 5 7 7]
0.23302589176575175
Iteration:  20
[7 2 7 ... 6 9 7] [2 2 9 ... 5 7 7]
0.43182575841760196
Iteration:  30
[2 2 9 ... 6 2 7] [2 2 9 ... 5 7 7]
0.46716301811312366
Iteration:  40
[2 0 9 ... 6 9 7] [2 2 9 ... 5 7 7]
0.5153905989554395
Iteration:  50
[2 0 4 ... 1 7 7] [2 2 9 ... 5 7 7]
0.6578508723191465
Iteration:  60
[2 0 4 ... 8 7 7] [2 2 9 ... 5 7 7]
0.672852539171019
Iteration:  70
[6 0 4 ... 8 7 7] [2 2 9 ... 5 7 7]
0.6886320702300256
Iteration:  80
[6 0 4 ... 5 7 7] [2 2 9 ... 5 7 7]
0.7044116012890321
Iteration:  90
[6 0 4 ... 5 7 7] [2 2 9 ... 5 7 7]
0.7239693299255473
Iteration:  100
[6 0 4 ... 5 7 7] [2 2 9 ... 5 7 7]
0.7427491943549284
Iteration:  110
[2 0 4 ... 5 7 7] [2 2 9 ... 5 7 7]
0.7574174908323147
Iteration:  120
[2 2 4 ... 5 2 7] [2 2 9 ... 5 7 7]
0.7869763307034114
Iteration:  130
[2 0 7 ... 5 7 7] [2 2 9 ... 5 7 7]
0.8102011334592732
Iteration:  14